


oauth2:
  google:
    client-id: 205578501902-2g0aj7mkvmtbpqdcjqt86nhc64euj7l0.apps.googleusercontent.com
    client-secret: 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
    redirect-uri: http://localhost:8080/login/oauth2/code/google
    token-uri: https://oauth2.googleapis.com/token
    resource-uri: https://www.googleapis.com/oauth2/v2/userinfo


spring:
  session:
    timeout: 86400
    store-type: jdbc
    jdbc.initialize-schema: always

jpa:
  open-in-view: false
  generate-ddl: true
